foreground #a4c6c4
background #091210
selection_foreground #53993F
selection_background #526657
cursor #a4c6c4
active_border_color #a4c6c4
inactive_border_color #091210
active_tab_foreground #a4c6c4
active_tab_background #091210
inactive_tab_foreground #a4c6c4
inactive_tab_background #091210
