foreground #a8bfe0
background #040916
selection_foreground #3D4A97
selection_background #3C437A
cursor #a8bfe0
active_border_color #a8bfe0
inactive_border_color #040916
active_tab_foreground #a8bfe0
active_tab_background #040916
inactive_tab_foreground #a8bfe0
inactive_tab_background #040916
