shadowscolor= 0x091210ff
rootcolor=0x091210ff
bordercolor=0x9BBB65ff
dropcolor=0x9BBB6555
splitcolor=0x9BBB65ff
focuscolor=0x629A5Dff
maximizescreencolor=0x9BBB65ff
urgentcolor=0xa4c6c4ff
scratchpadcolor=0x629A5Dff
globalcolor=0x629A5Dff
overlaycolor=0x9BBB65ff
