shadowscolor= 0x040916ff
rootcolor=0x040916ff
bordercolor=0x9A5EA5ff
dropcolor=0x9A5EA555
splitcolor=0x9A5EA5ff
focuscolor=0x5A549Aff
maximizescreencolor=0x9A5EA5ff
urgentcolor=0xa8bfe0ff
scratchpadcolor=0x5A549Aff
globalcolor=0x5A549Aff
overlaycolor=0x9A5EA5ff
